### ISSUE TITLE
error: function `create_schema_migrations_table_if_needed` is private

### ISSUE THREAD

**Issue by aeikenberry** [sgrif/diesel#235] opened 2016-03-13 01:28 UTC
I'm new to Rust and Diesel, but when I try `cargo install diesel_cli` i get the following error:
```
   Compiling diesel_cli v0.5.1
.cargo/registry/src/github.com-88ac128001ac3a9a/diesel_cli-0.5.1/src/database.rs:133:44: 133:96 error: function `create_schema_migrations_table_if_needed` is private
.cargo/registry/src/github.com-88ac128001ac3a9a/diesel_cli-0.5.1/src/database.rs:133         try!(call_with_conn!(database_url, migrations::create_schema_migrations_table_if_needed));
                                                                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.cargo/registry/src/github.com-88ac128001ac3a9a/diesel_cli-0.5.1/src/database.rs:133:14: 133:97 note: in this expansion of call_with_conn! (defined in .cargo/registry/src/github.com-88ac128001ac3a9a/diesel_cli-0.5.1/src/database.rs)
.cargo/registry/src/github.com-88ac128001ac3a9a/diesel_cli-0.5.1/src/database.rs:133:9: 133:99 note: in this expansion of try! (defined in <std macros>)
.cargo/registry/src/github.com-88ac128001ac3a9a/diesel_cli-0.5.1/src/database.rs:133:44: 133:96 error: function `create_schema_migrations_table_if_needed` is private
.cargo/registry/src/github.com-88ac128001ac3a9a/diesel_cli-0.5.1/src/database.rs:133         try!(call_with_conn!(database_url, migrations::create_schema_migrations_table_if_needed));
                                                                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.cargo/registry/src/github.com-88ac128001ac3a9a/diesel_cli-0.5.1/src/database.rs:133:14: 133:97 note: in this expansion of call_with_conn! (defined in .cargo/registry/src/github.com-88ac128001ac3a9a/diesel_cli-0.5.1/src/database.rs)
.cargo/registry/src/github.com-88ac128001ac3a9a/diesel_cli-0.5.1/src/database.rs:133:9: 133:99 note: in this expansion of try! (defined in <std macros>)
error: aborting due to 2 previous errors
failed to compile `diesel_cli v0.5.1`, intermediate artifacts can be found at `/Users/aaron/target-install`

Caused by:
  Could not compile `diesel_cli`.
```
Rust: `rustc 1.7.0 (a5d1e7a59 2016-02-29)`
Cargo: `cargo 0.8.0-nightly (28a0cbb 2016-01-17)`
Mac: `10.11.3`

If I'm just being a noob, I apologize in advance.  Thanks!

**Comment by mcasper** [comment] 2016-03-13 03:54
Hey @aeikenberry!

It looks like a PR got merged into the main Diesel crate recently (that diesel_cli depends on) that is causing this issue, I'll get this fixed real quick and investigate why our tests didn't catch this.

**Comment by mcasper** [comment] 2016-03-13 04:07
Ah, so it looks like this is being caused by the currently published version of diesel_cli compiling diesel 0.5.3, which it does not play nicely with. Once @sgrif publishes a new version of diesel_cli, this should be fixed

**Comment by sgrif** [comment] 2016-03-13 04:08
Whoops, sorry about that. Publishing now

**Comment by sgrif** [comment] 2016-03-13 04:11
Should be good now

**Closed by sgrif** 2016-03-13 04:11 UTC

**Comment by metmirr** [comment] 2016-08-14 13:24
I am getting same error:
```

failed to compile `diesel_cli v0.7.1`, intermediate artifacts can be found at `/home/user/target-install`

Caused by:
  Could not compile `diesel`.

```

**Comment by sgrif** [comment] 2016-08-14 15:20
Can you open a new issue and provide the full error?
